# Generated by Django 2.1.14 on 2019-11-24 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rack',
            name='pdus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Pdu'),
        ),
    ]
