# Generated by Django 2.1.14 on 2019-11-24 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191124_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdu',
            name='brand',
            field=models.CharField(choices=[('apc', 'APC'), ('cyberpower', 'Cyberpower'), ('hp', 'HP'), ('tripp_lite', 'Tripp Lite')], default='test', max_length=30),
        ),
        migrations.AlterField(
            model_name='rack',
            name='height',
            field=models.PositiveIntegerField(choices=[(1, '1.0m'), (2, '2.0m'), (3, '3.0m'), (4, '4.0m'), (5, '5.0m')]),
        ),
        migrations.AlterField(
            model_name='rack',
            name='location',
            field=models.CharField(choices=[('N', 'North'), ('S', 'South'), ('W', 'West'), ('E', 'East')], max_length=200),
        ),
        migrations.AlterField(
            model_name='rack',
            name='pdus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Pdu'),
        ),
    ]
