# Generated by Django 2.1.14 on 2019-11-24 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191124_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='pdus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Pdu'),
        ),
    ]
